---
- name: Create a sandbox instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    key_name: rdops 
    instance_type: t2.micro
    security_group: rdops-sg
    image: ami-25250840
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-a3421cca
        assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: item.public_ip
        groupname: aws
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 180
        state: started
      with_items: "{{ ec2.instances }}"


    - name: Add tag to Instance(s)
      ec2_tag: resource={{ item.id }} region={{ us-east-2 }} state=present
      instance_tags:
        db: ldapserver
      with_items: "{{ ec2.instances }}"

#    - include: install_config_ldapserver.yml
    
# Start stopped instances specified by tag
#
#   - local_action:
#       module: ec2
#       instance_tags:
#         Name: ldapserver
#     state: running

#
# Restart instances specified by tag
#
#   - local_action:
#       module: ec2
#       instance_tags:
#         Name: ldapserver
#     state: restarted
    
